SYSTEM:
  #å¹³å°åç§° é‚®ä»¶æ–‡æ¡£ç­‰ä¼šç”¨åˆ°
  SYS_TITLE: "Fastcow Devops"
  #å¹³å°é“¾æ¥ ç”¨äºå‘é€é‚®ä»¶ç­‰é€šçŸ¥å¯èƒ½ä¼šç”¨åˆ° é…ç½®ä¸ºå‰ç«¯åœ°å€
  SYS_LINK: "https://localhost"
  #APIæ–‡æ¡£æè¿°
  SYS_DESCRIPTION: "
    Fastcow Devops APIæ–‡æ¡£. ğŸš€


    [GitHub](https://github.com/cary997/fastcow-devops)
    "
  #ç³»ç»Ÿç‰ˆæœ¬
  SYS_VERSION: "v1.0.1"
  #routerçš„å‰ç¼€
  SYS_ROUTER_PREFIX: "/v1"
  #ç™»å½•æ¥å£çš„url
  SYS_ROUTER_AUTH2: "/access-token"
  #åˆ·æ–°tokenæ¥å£çš„url
  SYS_ROUTER_REFRESH: "/refresh-token"
  #å‰ç«¯åŒæ­¥åŠ¨æ€è·¯ç”±æ¥å£çš„url
  SYS_ROUTER_SYNCROUTES: "/async-routes"
  # å…³é—­api docsåˆ™æ›´æ”¹ä¸ºnull
  SYS_OPENAPI_URL: "/openapi.json"
  # ç³»ç»Ÿæ—¶åŒº
  SYS_TIMEZONE: "Asia/Shanghai"

CORS:
  # è·¨åŸŸé…ç½®
  CORS_ORIGINS: ["*"]
  CORS_ALLOW_CREDENTIALS: True
  CORS_ALLOW_METHODS: ["*"]
  CORS_ALLOW_HEADERS: ["*"]

LOG:
  # æ—¥å¿—è·¯å¾„
  LOG_PATH:
    "logs/fastapi-naive.log"
    # ä¸ºTrueæ—¶åºåˆ—åŒ–æ—¥å¿—æ ¼å¼ä¸ºJSON
  LOG_SERIALIZE: False
  # æ—¥å¿—çº§åˆ«
  LOG_LEVER: "DEBUG"
  # æ—¥å¿—åˆ‡å‰²æ—¶é—´(æ¯å¤©)
  LOG_ROTATION_TIME: "00:00:00"
  # æ—¥å¿—åˆ‡å‰²å¤§å°
  LOG_ROTATION_SIZE: "500 MB"
  # æ—¥å¿—ä¿ç•™æ—¶é—´
  LOG_RETENTION: "15 days"
  # æ˜¯å¦è¾“å‡ºæ§åˆ¶å°ï¼ŒFalseä¸ºä¸è¾“å‡º
  LOG_CONSOLE: True
  # æ˜¯å¦è¾“å‡ºåˆ°æ–‡ä»¶ï¼ŒFalseä¸ºä¸è¾“å‡º
  LOG_FILE: False

SECURITY:
  # å¯†ç åŠ å¯†KEY 16ä½æ•°å­—å’Œå­æ¯
  SECRET_KEY: "TYK6tziA9azcb31d"
  SECRET_IV: "FD2fnb7ytFatHeem"
  # JWTåŠ å¯† openssl rand -hex 32
  SECRET_JWT_KEY: "26b38a12da2920855a9d839047525fa96f6fafc8a4c32379dd758e31022d33f3"
  SECRET_JWT_ALGORITHM: "HS256"
  # JWTè¿‡æœŸæ—¶é—´ï¼šåˆ†é’Ÿ
  SECRET_JWT_EXP: 10
  # JWTåˆ·æ–°ä»¤ç‰Œè¿‡æœŸæ—¶é—´ï¼šåˆ†é’Ÿ
  SECRET_REJWT_EXP: 180

DATABASE:
  # MYSQLåœ°å€
  DB_HOST: "127.0.0.1"
  # MYSQLç«¯å£
  DB_PORT: 3306
  # MYSQLæ•°æ®åº“åç§°
  DB_NAME: "fastcow"
  # MYSQLè¿æ¥ç”¨æˆ·
  DB_USER: "root"
  # MYSQLå¯†ç 
  DB_PASSWORD: "root123"
  # MYSQL queryè®¾ç½®
  DB_QUERY: 'charset=utf8mb4"'
  # æ˜¯å¦æ‰“å°sql
  DB_ECHO: False

CACHE:
  # standalone cluster sentinel
  #REDIS_MODE: 'cluster'
  REDIS_MODE: "standalone"
  # standaloneæ¨¡å¼é€‰æ‹©ä½¿ç”¨çš„åº“
  REDIS_DB: 0
  # standaloneï¼šIP:Portï¼Œclusterå’Œsentinelï¼šIP1:Port1,IP2:Port2,...
  #REDIS_ADDRESS: '192.168.10.10:6380,192.168.10.10:6381,192.168.10.10:6382,192.168.10.10:6383,192.168.10.10:6384,192.168.10.10:6385'
  REDIS_ADDRESS: "127.0.0.1:6379"
  # Username,æ²¡æœ‰åˆ™null
  REDIS_USERNAME: null
  # Password
  REDIS_PASSWORD: null
  # sentinel name
  REDIS_SENTINEL_NAME: null
  # ç¼–ç 
  REDIS_ENCODING: "utf-8"
  # æœ€å¤§è¿æ¥æ•°
  REDIS_MAX_CONNECTIONS: 50
  #æ˜¯å¦å¼€å¯SSL
  REDIS_SSL: False
  #SSl å¼ºåˆ¶æ‰§è¡Œä¸»æœºåéªŒè¯é»˜è®¤ä¸ºï¼šrequired
  REDIS_SSL_CERT_REQS: null
  #ssl caè¯ä¹¦è·¯å¾„/path/to/ca.pem
  REDIS_SSL_CA_CERTS: null

CELERY:
  # Broker Settings
  CELERY_BROKER_URL: "redis://127.0.0.1:6379/1"
  # The backend used to store task results (tombstones)
  # å¦‚æœä½¿ç”¨DATABASEè®¾ç½® åˆ™å¡«å†™DATABASEå³å¯
  CELERY_RESULT_BACKEND: "redis://127.0.0.1:6379/0"
  # Time (in seconds, or a timedelta object) for when after stored task tombstones will be deleted.
  CELERY_RESULT_EXPIRES: 864000
  # How many messages to prefetch at a time multiplied by the number of concurrent processe
  CELERY_CELERYD_PREFETCH_MULTIPLIER: 5
  # Maximum number of tasks a pool worker process can execute before itâ€™s replaced with a new one. Default is no limit
  CELERY_WORKER_MAX_TASKS_PER_CHILD: 100
  # Disable all rate limits, even if tasks has explicit rate limits set
  CELERY_WORKER_DISABLE_RATE_LIMITS: True
  # If enabled dates and times in messages will be converted to use the UTC timezone.
  CELERY_ENABLE_UTC: False
